# Generated by Django 5.1 on 2025-01-27 04:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gcarreira', '0001_initial'),
        ('gfuncionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anos_AD',
            fields=[
                ('id_anos', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anos_de_avaliacao', models.CharField(blank=True, max_length=225, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sgrh"."ad_anos',
            },
        ),
        migrations.CreateModel(
            name='Gad_tipo_ad',
            fields=[
                ('id_tipo_ad', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_avaliacao', models.CharField(blank=True, max_length=100, null=True)),
                ('controlo_estado', models.CharField(blank=True, max_length=100, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
            ],
            options={
                'db_table': 'sgrh"."ad_tipo',
            },
        ),
        migrations.CreateModel(
            name='Gad_classificacao_servico',
            fields=[
                ('id_classificacao_servico', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_max', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_min', models.CharField(blank=True, max_length=100, null=True)),
                ('qualitativa', models.CharField(blank=True, max_length=100, null=True)),
                ('sigla', models.CharField(blank=True, max_length=10, null=True)),
                ('controlo_estado', models.CharField(blank=True, max_length=100, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
                ('regime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcarreira.gcarreira_regime')),
            ],
            options={
                'db_table': 'sgrh"."ad_classificacao',
            },
        ),
        migrations.CreateModel(
            name='Gad_ficha_avaliacao_desempenho',
            fields=[
                ('id_avaliacao_desempenho', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantitativa', models.CharField(max_length=10)),
                ('qualitativa', models.CharField(max_length=10)),
                ('avaliador', models.CharField(blank=True, max_length=100, null=True)),
                ('data_ad', models.DateField(blank=True, null=True)),
                ('controlo_estado', models.CharField(blank=True, max_length=100, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
                ('ano_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gavaliacao_desempenho.anos_ad')),
                ('classificacao_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gavaliacao_desempenho.gad_classificacao_servico')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gfuncionarios.funcionarios')),
                ('tipo_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gavaliacao_desempenho.gad_tipo_ad')),
            ],
            options={
                'db_table': 'sgrh"."ad_ficha_avaliacao_desempenho',
            },
        ),
    ]
