# Generated by Django 5.1 on 2025-01-27 04:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gfuncionarios', '0001_initial'),
        ('master', '0002_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardHabilitacao',
            fields=[
                ('id_habilitacao', models.UUIDField(primary_key=True, serialize=False)),
                ('nivel_habilitacao', models.IntegerField()),
                ('total_habilitacao', models.IntegerField()),
            ],
            options={
                'db_table': 'sgrh"."view_dashboard_habilitacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewMonitorHabilitacao',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=225, null=True)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('id_sigap', models.CharField(blank=True, max_length=20, null=True)),
                ('data_inicio_habilitacao', models.DateField(default='1970-01-01')),
                ('data_fim_habilitacao', models.DateField(default='1970-01-01')),
                ('nivel_habilitacao', models.CharField(blank=True, max_length=50, null=True)),
                ('curso', models.CharField(blank=True, max_length=100, null=True)),
                ('entidade', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'sgrh"."view_monitor_habilitacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso_habilitacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_curso', models.CharField(blank=True, max_length=225, null=True)),
                ('sigla', models.CharField(blank=True, max_length=10, null=True)),
                ('controlo_estado', models.CharField(blank=True, max_length=100, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
            ],
            options={
                'db_table': 'sgrh"."hab_curso',
            },
        ),
        migrations.CreateModel(
            name='Nivel_habilitacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel_habilitacao', models.CharField(blank=True, max_length=225, null=True)),
                ('controlo_estado', models.CharField(blank=True, max_length=100, null=True)),
                ('ordem', models.CharField(blank=True, max_length=225, null=True)),
                ('pontos_promocao_rg', models.CharField(blank=True, max_length=100, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sgrh"."hab_nivel_habilitacao',
            },
        ),
        migrations.CreateModel(
            name='Entidade_habilitacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entidade', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_entidade', models.CharField(blank=True, max_length=100, null=True)),
                ('controlo_estado', models.CharField(blank=True, max_length=100, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.pais')),
            ],
            options={
                'db_table': 'sgrh"."hab_entidade',
            },
        ),
        migrations.CreateModel(
            name='Habilitacao_academica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_habilitacao', models.DateField(blank=True, null=True)),
                ('controlo_estado', models.CharField(blank=True, max_length=100, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habilitacao.curso_habilitacao')),
                ('entidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habilitacao.entidade_habilitacao')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gfuncionarios.funcionarios')),
                ('nivel_habilitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habilitacao.nivel_habilitacao')),
            ],
            options={
                'db_table': 'sgrh"."hab_habilitacao_academica',
            },
        ),
    ]
