# Generated by Django 5.1 on 2024-09-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sysname', models.CharField(max_length=100)),
                ('syssigla', models.CharField(blank=True, max_length=10, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Owner')),
                ('is_active', models.BooleanField(default=False)),
                ('nu_kontaktu', models.CharField(blank=True, max_length=10, null=True)),
                ('enderesu', models.CharField(blank=True, max_length=50, null=True)),
                ('about', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sgrh"."core',
            },
        ),
    ]
