# Generated by Django 5.1 on 2025-01-12 06:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sigla', models.CharField(blank=True, max_length=10, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Pais')),
            ],
            options={
                'db_table': 'sgrh"."pais',
            },
        ),
    ]
