# Generated by Django 5.1 on 2025-01-27 04:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gcarreira_categoria',
            fields=[
                ('id_categoria', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(blank=True, max_length=225, null=True)),
                ('base_legal', models.CharField(blank=True, max_length=20, null=True)),
                ('abreviatura', models.CharField(blank=True, max_length=20, null=True)),
                ('escalao_maximo', models.CharField(blank=True, max_length=20, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
            ],
            options={
                'db_table': 'sgrh"."gcarreira_categoria',
            },
        ),
        migrations.CreateModel(
            name='Gcarreira_composicao',
            fields=[
                ('id_composicao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('composicao', models.CharField(blank=True, max_length=225, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
            ],
            options={
                'db_table': 'sgrh"."gcarreira_composicao',
            },
        ),
        migrations.CreateModel(
            name='Gcarreira_regime',
            fields=[
                ('id_regime', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regime', models.CharField(blank=True, max_length=225, null=True)),
                ('base_legal', models.CharField(blank=True, max_length=100, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
            ],
            options={
                'db_table': 'sgrh"."gcarreira_regime',
            },
        ),
        migrations.CreateModel(
            name='Gcarreira_categoria_alias',
            fields=[
                ('id_categoria_alias', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria_alias', models.CharField(blank=True, max_length=225, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcarreira.gcarreira_categoria')),
            ],
            options={
                'db_table': 'sgrh"."gcarreira_categoria_alias',
            },
        ),
        migrations.CreateModel(
            name='Gcarreira_escalao',
            fields=[
                ('id_escalao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('escalao', models.CharField(blank=True, max_length=100, null=True)),
                ('escalao_numerico', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_grp', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data Inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esc_categoria', to='gcarreira.gcarreira_categoria')),
            ],
            options={
                'db_table': 'sgrh"."gcarreira_escalao',
            },
        ),
        migrations.CreateModel(
            name='Gcarreira_indice',
            fields=[
                ('id_indice', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indice', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data Inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
                ('composicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcarreira.gcarreira_composicao')),
                ('escalao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind_escalao', to='gcarreira.gcarreira_escalao')),
            ],
            options={
                'db_table': 'sgrh"."gcarreira_indice',
            },
        ),
        migrations.AddField(
            model_name='gcarreira_categoria',
            name='regime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_regime', to='gcarreira.gcarreira_regime'),
        ),
    ]
