# Generated by Django 5.1 on 2025-01-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioPivotGISEXO',
            fields=[
                ('grupu_idade', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('masculino', models.IntegerField()),
                ('feminino', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'sgrh"."view_statis_grupu_idade_sexo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FuncionarioPivotLTSEXO',
            fields=[
                ('local_trabalho', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('masculino', models.IntegerField()),
                ('feminino', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'sgrh"."view_statis_local_trabalho_sexo',
                'managed': False,
            },
        ),
    ]
