# Generated by Django 5.1 on 2025-01-27 04:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gcarreira', '0001_initial'),
        ('gfuncionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_casual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('controlo_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
            ],
            options={
                'db_table': 'sgrh"."categoria_casual',
            },
        ),
        migrations.CreateModel(
            name='Motivo_nao_exercicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('controlo_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
            ],
            options={
                'db_table': 'sgrh"."motivo_nao_exercicio',
            },
        ),
        migrations.CreateModel(
            name='Motivo_saida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('controlo_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
            ],
            options={
                'db_table': 'sgrh"."motivo_saida',
            },
        ),
        migrations.CreateModel(
            name='Relacao_juridica_emprego',
            fields=[
                ('id_rje', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relacao_juridica_emprego', models.CharField(blank=True, max_length=100, null=True)),
                ('controlo_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
            ],
            options={
                'db_table': 'sgrh"."relacao_juridica_emprego',
            },
        ),
        migrations.CreateModel(
            name='Tipo_alteracao_ficha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_alteracao_ficha', models.CharField(blank=True, max_length=100, null=True)),
                ('controlo_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
            ],
            options={
                'db_table': 'sgrh"."tipo_alteracao_ficha',
            },
        ),
        migrations.CreateModel(
            name='Tipo_casual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('controlo_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
            ],
            options={
                'db_table': 'sgrh"."tipo_casual',
            },
        ),
        migrations.CreateModel(
            name='Tipo_nomeacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_nomeacao', models.CharField(blank=True, max_length=100, null=True)),
                ('controlo_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
            ],
            options={
                'db_table': 'sgrh"."tipo_nomeacao',
            },
        ),
        migrations.CreateModel(
            name='Ficha_nao_exercicio',
            fields=[
                ('id_nao_exercicio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data Inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('controlo_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gfuncionarios.funcionarios')),
                ('motivo_nao_exercicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcao.motivo_nao_exercicio')),
            ],
            options={
                'db_table': 'sgrh"."ficha_nao_exercicio',
            },
        ),
        migrations.CreateModel(
            name='Ficha_saida_definitiva',
            fields=[
                ('id_saida', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data Saida')),
                ('controlo_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gfuncionarios.funcionarios')),
                ('motivo_saida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcao.motivo_saida')),
            ],
            options={
                'db_table': 'sgrh"."ficha_saida_definitiva',
            },
        ),
        migrations.CreateModel(
            name='Ficha_permanente',
            fields=[
                ('id_permanente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data Inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('data_inicio_categoria', models.DateField(blank=True, null=True, verbose_name='Data Inicio Categoria')),
                ('controlo_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gcarreira.gcarreira_categoria')),
                ('escalao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcarreira.gcarreira_escalao')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gfuncionarios.funcionarios')),
                ('indice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcarreira.gcarreira_indice')),
                ('regime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gcarreira.gcarreira_regime')),
                ('relacao_juridica_emprego', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcao.relacao_juridica_emprego')),
                ('tipo_alteracao_ficha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcao.tipo_alteracao_ficha')),
            ],
            options={
                'db_table': 'sgrh"."funcao_permanente',
            },
        ),
        migrations.CreateModel(
            name='Ficha_contratacao',
            fields=[
                ('id_contratacao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data Inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('controlo_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gcarreira.gcarreira_categoria')),
                ('escalao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcarreira.gcarreira_escalao')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gfuncionarios.funcionarios')),
                ('indice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcarreira.gcarreira_indice')),
                ('regime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gcarreira.gcarreira_regime')),
                ('relacao_juridica_emprego', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcao.relacao_juridica_emprego')),
                ('tipo_alteracao_ficha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcao.tipo_alteracao_ficha')),
            ],
            options={
                'db_table': 'sgrh"."funcao_contratacao',
            },
        ),
        migrations.CreateModel(
            name='Ficha_casual',
            fields=[
                ('id_casual', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data Inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('indice_casual', models.CharField(blank=True, max_length=50, null=True)),
                ('controlo_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gcarreira.gcarreira_categoria')),
                ('categoria_casual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcao.categoria_casual')),
                ('escalao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcarreira.gcarreira_escalao')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gfuncionarios.funcionarios')),
                ('indice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcarreira.gcarreira_indice')),
                ('regime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gcarreira.gcarreira_regime')),
                ('tipo_casual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcao.tipo_casual')),
            ],
            options={
                'db_table': 'sgrh"."funcao_casuais',
            },
        ),
        migrations.CreateModel(
            name='Ficha_comissao_servico',
            fields=[
                ('id_comissao_servico', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data Inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('controlo_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Inserido por')),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gcarreira.gcarreira_categoria')),
                ('escalao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcarreira.gcarreira_escalao')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gfuncionarios.funcionarios')),
                ('indice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcarreira.gcarreira_indice')),
                ('regime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gcarreira.gcarreira_regime')),
                ('relacao_juridica_emprego', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcao.relacao_juridica_emprego')),
                ('tipo_alteracao_ficha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcao.tipo_alteracao_ficha')),
                ('tipo_nomeacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcao.tipo_nomeacao')),
            ],
            options={
                'db_table': 'sgrh"."funcao_comissao_servico',
            },
        ),
    ]
