# Generated by Django 5.1 on 2025-01-27 04:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gdivisao_administrativa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituicaoReport',
            fields=[
                ('instituicao_id', models.UUIDField(primary_key=True, serialize=False)),
                ('total_seccoes', models.IntegerField()),
                ('total_departamentos', models.IntegerField()),
                ('total_direcoes_nacionais', models.IntegerField()),
                ('total_direcoes_gerais', models.IntegerField()),
            ],
            options={
                'db_table': 'sgrh"."view_instituicao_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=225, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data Inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('controlo_ativo', models.CharField(blank=True, max_length=225, null=True)),
                ('descricao', models.CharField(blank=True, max_length=225, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
            ],
            options={
                'db_table': 'sgrh"."ministerio_instituicao',
            },
        ),
        migrations.CreateModel(
            name='Direcao_geral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=225, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data Inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('controlo_ativo', models.CharField(blank=True, max_length=225, null=True)),
                ('descricao', models.CharField(blank=True, max_length=225, null=True)),
                ('equiparacao', models.BooleanField(default=False)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gdivisao_administrativa.gdivisao_administrativa_municipio')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dg_inst', to='unidade_ministerio.instituicao')),
            ],
            options={
                'db_table': 'sgrh"."ministerio_direcao_geral',
            },
        ),
        migrations.CreateModel(
            name='Direcao_nacional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=225, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data Inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('controlo_ativo', models.CharField(blank=True, max_length=225, null=True)),
                ('descricao', models.CharField(blank=True, max_length=225, null=True)),
                ('equiparacao', models.BooleanField(default=False)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
                ('dg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dn_dg', to='unidade_ministerio.direcao_geral')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gdivisao_administrativa.gdivisao_administrativa_municipio')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dn_inst', to='unidade_ministerio.instituicao')),
            ],
            options={
                'db_table': 'sgrh"."ministerio_direcao_nacional',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=225, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data Inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('controlo_ativo', models.CharField(blank=True, max_length=225, null=True)),
                ('descricao', models.CharField(blank=True, max_length=225, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gdivisao_administrativa.gdivisao_administrativa_municipio')),
                ('dg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dep_dg', to='unidade_ministerio.direcao_geral')),
                ('dn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dep_dn', to='unidade_ministerio.direcao_nacional')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_inst', to='unidade_ministerio.instituicao')),
            ],
            options={
                'db_table': 'sgrh"."ministerio_departamento',
            },
        ),
        migrations.CreateModel(
            name='Seccao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=225, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data Inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('controlo_ativo', models.CharField(blank=True, max_length=225, null=True)),
                ('descricao', models.CharField(blank=True, max_length=225, null=True)),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
                ('dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sec_dep', to='unidade_ministerio.departamento')),
                ('dg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sec_dg', to='unidade_ministerio.direcao_geral')),
                ('dn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sec_dn', to='unidade_ministerio.direcao_nacional')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sec_inst', to='unidade_ministerio.instituicao')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gdivisao_administrativa.gdivisao_administrativa_municipio')),
            ],
            options={
                'db_table': 'sgrh"."ministerio_seccao',
            },
        ),
    ]
