# Generated by Django 5.1 on 2025-01-27 04:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewDivisaoAdministrativa',
            fields=[
                ('id_municipio', models.UUIDField(primary_key=True, serialize=False)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inicio_municipio', models.DateField(default='1970-01-01')),
                ('data_fim_municipio', models.DateField(default='1970-01-01')),
                ('posto', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inicio_posto', models.DateField(default='1970-01-01')),
                ('data_fim_posto', models.DateField(default='1970-01-01')),
                ('suco', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inicio_suco', models.DateField(default='1970-01-01')),
                ('data_fim_suco', models.DateField(default='1970-01-01')),
                ('aldeia', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inicio_aldeia', models.DateField(default='1970-01-01')),
                ('data_fim_aldeia', models.DateField(default='1970-01-01')),
            ],
            options={
                'db_table': 'sgrh"."view_divisao_administrativa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gdivisao_administrativa_municipio',
            fields=[
                ('id_municipio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('municipio', models.CharField(blank=True, max_length=225, null=True)),
                ('codigo_municipio', models.CharField(blank=True, max_length=20, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data Inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
            ],
            options={
                'db_table': 'sgrh"."gdivisao_administrativa_municipio',
            },
        ),
        migrations.CreateModel(
            name='Gdivisao_administrativa_posto',
            fields=[
                ('id_posto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('posto', models.CharField(blank=True, max_length=225, null=True)),
                ('codigo_posto', models.CharField(blank=True, max_length=20, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data Inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postos', to='gdivisao_administrativa.gdivisao_administrativa_municipio')),
            ],
            options={
                'db_table': 'sgrh"."gdivisao_administrativa_posto',
            },
        ),
        migrations.CreateModel(
            name='Gdivisao_administrativa_suco',
            fields=[
                ('id_suco', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suco', models.CharField(blank=True, max_length=225, null=True)),
                ('codigo_suco', models.CharField(blank=True, max_length=20, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data Inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
                ('posto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucos', to='gdivisao_administrativa.gdivisao_administrativa_posto')),
            ],
            options={
                'db_table': 'sgrh"."gdivisao_administrativa_suco',
            },
        ),
        migrations.CreateModel(
            name='Gdivisao_administrativa_aldeia',
            fields=[
                ('id_aldeia', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aldeia', models.CharField(blank=True, max_length=225, null=True)),
                ('codigo_aldeia', models.CharField(blank=True, max_length=20, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data Inicio')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('inserido_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('inserido_por', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alterado por')),
                ('suco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aldeias', to='gdivisao_administrativa.gdivisao_administrativa_suco')),
            ],
            options={
                'db_table': 'sgrh"."gdivisao_administrativa_aldeia',
            },
        ),
    ]
